#!/usr/bin/env ruby
require File.dirname(__FILE__) + "/../config/environment" unless defined?(RAILS_ROOT)
require "unused_translations"

if ARGV[0]
  puts UnusedTranslations.main(ARGV[0]).to_yaml
else
  puts "Usage: script/unused_translations config/locales/en.yml" 
end
